version: "3.8"
services:
  postgresdb:
    image: postgres:16
    container_name: postgresdb
    restart: always
    environment:
      - APP_ENVIRONMENT=DEV
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gigalogy-dev
  init-db:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: init-db
    environment:
      APP_ENVIRONMENT: DEV
      PYTHONPATH: /app
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      MAIRA_API_HOSTNAME: $MAIRA_API_HOSTNAME
      MAIRA_API_PORT: $MAIRA_API_PORT
      MAIRA_API_URL: $MAIRA_API_URL
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_API_URL: $OPENAI_API_URL
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "PYTHONPATH=/app python src/db/define_tables.py"
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - gigalogy-dev
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      APP_ENVIRONMENT: DEV
      PYTHONPATH: /app
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      MAIRA_API_HOSTNAME: $MAIRA_API_HOSTNAME
      MAIRA_API_PORT: $MAIRA_API_PORT
      MAIRA_API_URL: $MAIRA_API_URL
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_API_URL: $OPENAI_API_URL
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "PYTHONPATH=/app uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      postgresdb:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully
    networks:
      - gigalogy-dev
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend/app:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: bash -c "npm run dev -- --host"
    depends_on:
      - fastapi
    networks:
      - gigalogy-dev

volumes:
  postgres_data:
  node_modules:

networks:
  gigalogy-dev:
    external: true
